# docker-compose.yml

services:
  db:
    image: postgres:16
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 10s
      retries: 5

  fastapi:
    build: ./fastapi-app
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"

  grafana:
    image: grafana/otel-lgtm:latest
    env_file: .env
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD}
      DS_POSTGRES_HOST: db:5432
      DS_POSTGRES_USER: ${POSTGRES_USER}
      DS_POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      DS_POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
    depends_on:
      db:
        condition: service_started
    ports:
      - "3000:3000"
      - "4317:4317" # OTLP gRPC
      - "4318:4318" # OTLP HTTP
    healthcheck:
      test: ["CMD-SHELL", "curl -fs http://localhost:3000/api/health | grep -q '\"ok\"'"]
      interval: 15s
      start_period: 30s
      retries: 5

  # superset:
  #   build: ./superset
  #   env_file: .env
  #   environment:
  #     SUPERSET_DATABASE_URI: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
  #     SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
  #     SUPERSET_ADMIN_USER: ${SUPERSET_ADMIN_USER}
  #     SUPERSET_ADMIN_PASSWORD: ${SUPERSET_ADMIN_PASSWORD}
  #   volumes:
  #     - superset-data:/app/superset_home
  #   depends_on:
  #     db:
  #       condition: service_healthy
  #     fastapi:
  #       condition: service_started
  #   ports:
  #     - "8088:8088"

volumes:
  pgdata:
  grafana-data:
  # superset-data:
